# Generated by Django 5.0.6 on 2024-06-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_newtest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
