# Generated by Django 5.0.6 on 2024-06-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0006_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.CharField(
                default="https://media.istockphoto.com/id/1500059583/photo/telluride-colorado-in-fall-color.jpg?s=2048x2048&w=is&k=20&c=8hx5S-0JHIsaslHSOmYkFaJ66axxBFvJD0XTsoCPuC4=",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.IntegerField(
                choices=[(0, "pending"), (1, "逾期"), (2, "cancelled")], default=0
            ),
        ),
    ]
