# Generated by Django 5.0.6 on 2024-06-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0008_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/static/img/ustcblack.jpg",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
