# Generated by Django 5.0.6 on 2024-06-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0009_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
